file_format: "1"
id: nyx
name: Nyx Split
type: shield
url: https://github.com/yourname/nyx-split
requires: [pro_micro]
features:
  - keys
  - wireless
  - battery
siblings:
  - nyx_left
  - nyx_right
